name: 'Jira Assign Action'
author: "Fikunmi Samson"
description: 'Assign a Jira ticket to a team member'
inputs:
  jira_base_url:
    description: 'Jira base URL'
    required: true
  jira_user_email:
    description: 'Jira user email'
    required: true
  jira_api_token:
    description: 'Jira API token'
    required: true
  jira_ticket:
    description: 'Jira ticket key'
    required: true
  jira_assignee:
    description: 'Jira assignee username'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install requests library
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Assign Jira ticket
      shell: bash
      env:
        JIRA_BASE_URL: ${{ inputs.jira_base_url }}
        JIRA_USER_EMAIL: ${{ inputs.jira_user_email }}
        JIRA_API_TOKEN: ${{ inputs.jira_api_token }}
        JIRA_TICKET: ${{ inputs.jira_ticket }}
        JIRA_ASSIGNEE: ${{ inputs.jira_assignee }}
      run: python ${{ github.action_path }}/assign_ticket.py
branding:
  icon: "activity"
  color: "blue"